name: PoorWorld
version: 1.0
main: com.gmail.jobstone.PoorWorld
description: A plugin.
author: Jobstone
api-version: 1.13
commands:
    poorworld:
        aliases: pw
        usage: /<command>
        permission: poorworld.basic
        permission-message: You don't have permission:<permission>
permissions:
    poorworld.basic:
        description: Gives access.
        default: true